workflows:
  build-android:
    name: Build Android (Free Plan)
    instance_type: linux_x2   # مجاني
    max_build_duration: 60    # أقصى مدة للبناء بالدقائق
    environment:
      node: 16.20.0
      npm: 8.19.4
      java: 11
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android release
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
