workflows:
  build-android:
    name: Build Android (Free Plan)
    max_build_duration: 60
    environment:
      node: 16.20.0
      npm: 8.19.4
      java: 11
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android release
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
