workflows:
  react-native-android:
    name: Build Android
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      vars:
        PACKAGE_NAME: "com.yourapp"
      node: 16.20.0
      npm: 8.19.4
      java: 11
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
